module.exports = {
    'likes': '{likes, number} me gusta',
    'logout': 'Salir',
    'english': 'Ingles',
    'spanish': 'Español',
    'signup.subheading': 'Registrate para ver fotos de tus amigos estudiando en Platzi',
    'signup.facebook': 'Iniciar sesion con Facebook',
    'signup.text': 'Iniciar sesion',
    'email': 'Correo Electronico',
    'username': 'Nombre de usuario',
    'fullname': 'Nombre completo',
    'password': 'Contraseña',
    'signup.call-to-action': 'Registrate',
    'signup.have-account': 'Tienes una cuenta',
    'signin': 'Entrar',
    'signin.not-have-account': 'No tienes una cuenta?',
    'language': 'Lenguaje',
    'upload-picture': 'Subir foto',
    'upload': "Subir"
}
